#!/bin/bash

session=dashboard
set -e
cd "$(git rev-parse --show-toplevel)"

if [ ! "$1" ]; then
  echo "Usage: $0 [hostname]"
  exit 1
fi

tmux -2 new-session -d -s "$session" -A "./baxter.sh $1"
# tmux new-window -n "frontend"
tmux split-window -h "./baxter.sh $1"
tmux split-window -v "./baxter.sh $1"
tmux select-pane -t 0
tmux split-window -v "./baxter.sh $1"

tmux send-keys "roslaunch tetris baxter_moveit_headless.launch" C-m
tmux select-pane -t 0
tmux send-keys "roslaunch ar_track_alvar camera_track.launch" C-m

tmux -2 attach-session -t "$session"
