#!/bin/bash

session=pap
set -e
cd "$(git rev-parse --show-toplevel)"

if [ ! "$1" ]; then
  echo "Usage: $0 [hostname]"
  exit 1
fi

export ROS_MASTER_URI=http://$1:11311
tmux -2 new-session -d -s "$session" -A "./baxter.sh $1"
# tmux new-window -n "frontend"
tmux split-window -h "./baxter.sh $1"
tmux split-window -v "./baxter.sh $1"
tmux select-pane -t 0
tmux split-window -v "./baxter.sh $1"

tmux send-keys "rosrun baxter_tools enable_robot.py -e" C-m
tmux select-pane -t 0
tmux send-keys "rosrun baxter_interface joint_trajectory_action_server.py" C-m
tmux select-pane -t 2
tmux send-keys "roslaunch baxter_moveit_config demo_baxter.launch right_electric_gripper:=true left_electric_gripper:=true" C-m

tmux -2 attach-session -t "$session"
